#!/bin/sh

case "$1" in
    start)
        if grep -q '^staff:' /etc/group; then
            group="staff"
        else
            group="wheel"
        fi
        insmod /lib/modules/$(uname -r)/extra/aesdchar.ko
        #echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
        major=$(awk "\$2==\"aesdchar\" {print \$1}" /proc/devices)
        if [ ! -z ${major} ]; then
            #echo "Remove any existing /dev node for /dev/${device}"
            rm -f /dev/aesdchar
            #echo "Add a node for our device at /dev/${device} using mknod"
            mknod /dev/aesdchar c $major 0
            #echo "Change group owner to ${group}"
            chgrp $group /dev/${device}
            #echo "Change access mode to ${mode}"
            chmod 664 /dev/${device}
        else
            echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
        fi
        ;;
    stop)
        # invoke rmmod with all arguments we got
        rmmod aesdchar

        # Remove stale nodes

        rm -f /dev/aesdchar
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0